---
apiVersion: v1
kind: Secret
metadata:
  name: sysdig-monitor-api-token
  namespace: custom-metrics
type: Opaque
data:
  # This is not a valid agent key! You should create your own, e.g.:
  #
  #     $ kubectl delete secret sysdig-monitor-api-token --namespace=custom-metrics
  #
  #     $ kubectl create secret generic sysdig-monitor-api-token \
  #           --namespace=custom-metrics \
  #           --from-literal=token=<YOUR OWN KEY>
  #
  #     $ kubectl get secret sysdig-monitor-api-token -o json
  #
  # You could also encode the key from the command-line interface and edit the
  # object manually, e.g.:
  #
  #   $ echo -n "59493980-bbab-44e5-81b2-d80d59192fcd" | base64
  #   NTk0OTM5ODAtYmJhYi00NGU1LTgxYjItZDgwZDU5MTkyZmNk
  #
  #   $ env KUBE_EDITOR=vim kubectl edit secret sysdig-monitor-api-token
  #
  # This is not a real token!
  token: NTk0OTM5ODAtYmJhYi00NGU1LTgxYjItZDgwZDU5MTkyZmNk

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: custom-metrics-apiserver
  namespace: custom-metrics
  labels:
    app: custom-metrics-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-metrics-apiserver
  template:
    metadata:
      labels:
        app: custom-metrics-apiserver
    spec:
      tolerations:
      - key: beta.kubernetes.io/arch
        value: arm
        effect: NoSchedule
      - key: beta.kubernetes.io/arch
        value: arm64
        effect: NoSchedule
      serviceAccountName: custom-metrics-apiserver
      volumes:
      - name: sysdig-monitor-api-token
        secret:
          secretName: sysdig-monitor-api-token
      containers:
      - name: custom-metrics-server
        image: sevein/k8s-sysdig-adapter:latest
        imagePullPolicy: Always
        command: ["adapter"]
        args:
        - "--namespace=default"
        - "--service=kuard"
        - "--logtostderr=true"
        - "--v=10"
        env:
        - name: SDC_TOKEN
          valueFrom:
            secretKeyRef:
              name: sysdig-monitor-api-token
              key: token
        ports:
        - containerPort: 443
        securityContext:
          runAsUser: 0
