# -*- mode: ruby -*-
# vi: set ft=ruby :

NETWORK = "172.17.8."
NETMASK = "255.255.255.0"
BOX = "bento/ubuntu-16.04"
WORKERS = ENV.has_key?('WORKERS') ? ENV['WORKERS'].to_i : 1
SYSDIG_ACCESS_KEY = ENV.has_key?('SYSDIG_ACCESS_KEY') ? ENV['SYSDIG_ACCESS_KEY'] : ""

HOSTS = {
  "controller-node" => [NETWORK+"100", 2000]
}
(1..WORKERS).each do |i|
  HOSTS["worker-node-#{i}"] = [NETWORK+"#{i+100}", 2000]
end

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  HOSTS.each do | (host, attrs) |
    ipaddr, ram = attrs
    config.vm.define host do |machine|
      machine.ssh.insert_key = false
      machine.ssh.username = "vagrant"
      machine.vm.hostname = host
      machine.vm.network 'private_network', ip: ipaddr, netmask: NETMASK
      machine.vm.box  = BOX
      machine.vm.guest = :debian
      machine.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.memory = ram
        vbox.name = host
        vbox.cpus = 2
      end
      machine.vm.provision "shell",
        path: "mixins/bootstrap.sh",
        args: [ipaddr, host, SYSDIG_ACCESS_KEY]
    end
  end

end
