package sdc

import (
	"fmt"
	"net/http"
	"testing"
	"time"
)

var (
	metricsJSONResponse = `
{
    "total": 48,
    "offset": 0,
    "metricDescriptors": [
        {
            "id": "jvm.class.loaded",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.class.unloaded",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.ConcurrentMarkSweep.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.ConcurrentMarkSweep.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.Copy.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.Copy.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.G1_Old_Generation.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.G1_Old_Generation.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.G1_Young_Generation.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.G1_Young_Generation.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.MarkSweepCompact.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.MarkSweepCompact.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.PS_MarkSweep.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.PS_MarkSweep.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.PS_Scavenge.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.PS_Scavenge.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.ParNew.count",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.ParNew.time",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.gc.collectors.old.collection_time",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.collectors.old.count",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.collectors.young.collection_time",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.gc.collectors.young.count",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.heap.committed",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.heap.init",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.heap.max",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.heap.used",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.heap.used.percent",
            "metricType": "gauge",
            "type": "%",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.mem.heap_committed",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.heap_in_use",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.heap_max",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.heap_used",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.non_heap_committed",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.non_heap_used",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.pools.old.max",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.pools.old.used",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.pools.survivor.max",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.pools.survivor.used",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.pools.young.max",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.mem.pools.young.used",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.nonHeap.committed",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.nonHeap.init",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.nonHeap.max",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.nonHeap.used",
            "metricType": "counter",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "timeAvg",
                "avg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "sum",
                "avg",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.nonHeap.used.percent",
            "metricType": "gauge",
            "type": "%",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.thread.count",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.thread.daemon",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "jmx",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false,
            "documented": true
        },
        {
            "id": "jvm.threads.count",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        },
        {
            "id": "jvm.threads.peak_count",
            "metricType": "gauge",
            "type": "number",
            "scale": 1,
            "category": "appinfo",
            "namespaces": [
                "host",
                "host.process",
                "host.container",
                "cloudProvider",
                "mesos",
                "ecs",
                "kubernetes.cluster",
                "kubernetes.namespace",
                "kubernetes.deployment",
                "kubernetes.job",
                "kubernetes.daemonSet",
                "kubernetes.service",
                "kubernetes.node",
                "kubernetes.replicaSet",
                "kubernetes.statefulSet",
                "kubernetes.resourcequota",
                "kubernetes.persistentvolume",
                "kubernetes.persistentvolumeclaim",
                "kubernetes.pod"
            ],
            "scopes": [],
            "timeAggregations": [
                "avg",
                "timeAvg",
                "sum",
                "min",
                "max",
                "rateOfChange"
            ],
            "groupAggregations": [
                "avg",
                "sum",
                "min",
                "max"
            ],
            "identity": false,
            "canMonitor": false,
            "canGroupBy": false,
            "canFilter": false,
            "heuristic": false
        }
    ]
}
`

	getJSONResponse = `
{
  "data": [
    {
      "d": [0.127],
      "t": 1523864340
    },
    {
      "d": [0.128],
      "t": 1523864350
    }
  ],
  "start": 1523864330,
  "end": 1523864350
}`
)

func TestData_Metrics(t *testing.T) {
	setup()
	defer teardown()

	mux.HandleFunc("api/v2/metrics/descriptors", func(w http.ResponseWriter, r *http.Request) {
		testMethod(t, r, http.MethodGet)
		fmt.Fprint(w, metricsJSONResponse)
	})

	payload, _, err := client.Data.Metrics(ctx)
	if err != nil {
		t.Errorf("Data.Metrics returned error: %v", err)
	}

	if have, want := len(payload), 1; have != want {
		t.Errorf("Data.Metrics returned %d items, expected %d", have, want)
	}
}

func TestData_Get(t *testing.T) {
	setup()
	defer teardown()

	mux.HandleFunc("/data", func(w http.ResponseWriter, r *http.Request) {
		testMethod(t, r, http.MethodPost)
		fmt.Fprint(w, getJSONResponse)
	})

	req := &GetDataRequest{Last: -20, Sampling: 10}
	req = req.WithMetric("memory.used.percent", &MetricAggregation{Time: "timeAvg", Group: "avg"})
	payload, _, err := client.Data.Get(ctx, req)
	if err != nil {
		t.Errorf("Data.Get returned error: %v", err)
	}

	if have, want := len(payload.Samples), 2; have != want {
		t.Errorf("Data.Get returned %d samples, expected %d", have, want)
	}
	if have, want := payload.Start, Timestamp(time.Unix(1523864330, 0)); have != want {
		t.Fatalf("Data.Get returned %s, expected %s", have.String(), want.String())
	}
	if have, want := payload.End, Timestamp(time.Unix(1523864350, 0)); have != want {
		t.Fatalf("Data.Get returned %s, expected %s", have.String(), want.String())
	}
}
